sm_config.settings:
  type: config_object
  label: 'sm_config settings'
  mapping:
    routing:
      type: sequence
      sequence:
        type: mapping
        mapping:
          bus:
            type: string
          message:
            type: string
          receivers:
            type: sequence
            sequence:
              type: string
