name: 'ECA Config'
type: module
description: 'Config events.'
core_version_requirement: ^9 || ^10
package: ECA
dependencies:
  - eca:eca

# Information added by Drupal.org packaging script on 2024-08-16
version: '1.1.9'
project: 'eca'
datestamp: 1723822369
