<?php

use Drupal\Core\Cache\Cache;
use Drupal\Core\Url;
use Drupal\surgery\Constants\Constants;

/** 
 * Implements hook_page_attachments().
 */
function surgery_page_attachments(array &$attachments) {
  if (\Drupal::currentUser()->hasPermission('access coffee')) {
    $config = \Drupal::config('coffee.configuration');
    $cache_tags = isset($attachments['#cache']['tags']) ? $attachments['#cache']['tags'] : [];
    $attachments['#cache']['tags'] = Cache::mergeTags($cache_tags, $config->getCacheTags());
    // The /admin/surgery/coffee/get-data path.
    $data_path =  Url::fromRoute('surgery.coffee.get_data', ['query' => ' '], ['language' => \Drupal::languageManager()->getCurrentLanguage()])->toString();
    $attachments['#attached']['drupalSettings']['surgery']['coffee'] = [
      'dataPath' => $data_path,
      'maxResults' => $config->get('max_results'),
      'availableCommands' => Constants::getAvailableCommands(),
    ];
  }
}

/** 
 * Implements hook_preprocess_HOOK().
 */
function surgery_preprocess_table__tableselect(array &$variables) {
  // Target the table of Contrib modules provided Upgrade Status module,
  // make the labels active and open-in-new-tab links.
  if (\Drupal::moduleHandler()->moduleExists('upgrade_status')) {
    if ($variables['attributes']['id'] === 'edit-collaborate-data-list') {
      $index = 0;
      foreach ($variables['rows'] as &$row) {
        // column 1 is for the 2nd column, which are the labels.
        // column 0 is for the 1st column, which are checkboxes.
        $label = $row['cells'][1]['content']['label'];
        preg_match('#\((.*?)\)#', $label['#value'], $match);
        $machine_name = $match[1];
        $variables['rows'][$index]['cells'][1]['content'] = [
          '#type' => 'link',
          '#title' => $label['#value'],
          '#url' => Url::fromUri("https://www.drupal.org/project/{$machine_name}", ['absolute' => TRUE]),
          '#attributes' => [
            'target' => 'blank_',
          ]
        ];
        $index += 1;
      }
    }
  }
}

/** 
 * Implements hook_preprocess_HOOK().
 */
function surgery_preprocess_table(array &$variables) {
  /** @var array $target_table_ids */
  $target_table_ids = ['field-overview', 'surgery-table'];

  if (isset($variables['attributes']['id'])) {
    $table_id = $variables['attributes']['id'];

    // ddev drush route --path=/admin/structure/types/manage/resource/fields
    // The `entity.node.field_ui_fields` route.
    if ($table_id === 'field-overview') {
      $headers = &$variables['header'];
      $rows = &$variables['rows'];

      $headers['author'] = [
        'tag' => 'th',
        'content' => t('Author'),
        'attributes' => [],
      ];

      foreach ($rows as $key => &$row) {
        $cells = &$row['cells'];
        $cells['author'] = [
          'tag' => 'td',
          'attributes' => [],
          'content' => t('Hai Nguyen'),
        ];
      }

      $variables['header_columns'] += 1;
    }

    if (in_array($table_id, $target_table_ids)) {
      $variables['#attached']['drupalSettings']['surgery']['table_ids'][] = $variables['attributes']['id'];
      $variables['#attached']['library'][] = 'surgery/data_tables';
      // $variables['#attached']['library'][] = 'surgery/table_tweaks';
    }
  }
  else {
    $variables['attributes']['id'] = 'surgery-table';
    $variables['#attached']['drupalSettings']['surgery']['table_ids'][] = $variables['attributes']['id'];
    $variables['#attached']['library'][] = 'surgery/data_tables';
    // $variables['#attached']['library'][] = 'surgery/table_tweaks';
  }
}
