<?php

/**
 * @file
 * Hooks for eg_license_plate.
 */

/** 
 * Implements hook_theme().
 */
function eg_license_plate_theme($existing, $type, $theme, $path) {
  return [
    'license_plate' => [
      'variables' => [
        'code' => NULL,
        'number' => NULL,
        'concatenated' => FALSE,
      ],
    ],
    'snippets_code' => [
      'variables' => [
        'source_code' => NULL,
        'source_lang' => NULL,
        'source_description' => NULL,
      ],
    ],
  ];
}
