<?php

use Drupal\node\Entity\Node;

/**
 * Implements hook_preprocess_HOOK().
 */
function hnp_project_build_step_preprocess_field(array &$variables) {
  if (isset($variables['element']['#object'])) {
    $node = $variables['element']['#object'];
    if ($node instanceof Node 
      && $node->bundle() === 'project_build_step' 
      && isset($variables['field_name']) 
      && $variables['field_name'] === 'created'
    ) {
      $variables['items'][0]['content']['#markup'] = !$node->changed->isEmpty() 
        ? date('F d, Y', $node->changed->value) 
        : date('F d, Y', $node->created->value);
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function hnp_project_build_step_preprocess_node(array &$variables) {
  /** @var Drupal\node\Entity\Node */
  $node = $variables['node'];
  if ($node instanceof Node 
    && $node->bundle() === 'project_build_step' 
    && $node->hasField('field_related_build_steps')
  ) {
    // Determines if this `project_build_step` node has related contents or not.
    $variables['no_related_content'] = $node->field_related_build_steps->isEmpty();
  }
}

/**
 * Implement hook_preprocess_block()
 */
function hnp_project_build_step_preprocess_block(array &$variables) {
  if ($variables['plugin_id'] === 'page_title_block') {
    $current_path = \Drupal::service('path.current')->getPath();
    if (str_contains($current_path, 'projects') && str_contains($current_path, 'read-all')) {
      $tokens = explode('/', $current_path);
      foreach ($tokens as $index => $token) {
        if (is_numeric($token)) {
          $nid = $tokens[$index];
          $node = Node::load($nid);
          $label = $node->label();
          $variables['content']['#title']['#markup'] = "Build Steps for {$label}";
        }
      }
    }
  }
}
