# @see field.storage_settings.file in core/modules/file/config/schema/file.schema.yml file.
# Format: field.storage_settings.ID where ID is the id from @FieldType annotation.
field.storage_settings.license_plate:
  type: mapping
  label: "License plate storage settings"
  mapping:
    number_max_length:
      type: integer
      label: "Max length for the number"
    code_max_length:
      type: integer
      label: "Max length for the code"

# @see field.widget.settings.file_generic in core/modules/file/config/schema/file.schema.yml file.
# Format: field.widget.settings.ID where ID is the id from @FieldWidget annotation.
field.widget.settings.default_license_plate_widget:
  type: mapping
  label: "Default license plate widget settings"
  mapping:
    number_size:
      type: integer
      label: "Number size"
    code_size:
      type: integer
      label: "Code size"
    fieldset_state:
      type: string
      label: "The state of the fieldset which contains 2 values: open and closed"
    placeholder:
      type: mapping
      label: "The placeholder for the two fields"
      mapping:
        number:
          type: string
          label: "The placeholder for the number field"
        code:
          type: string
          label: "The placeholder for the code field"

# Format: field.formatter.settings.ID where ID is the id from @FieldFormatter annotation.
field.formatter.settings.default_license_plate_formatter:
  type: mapping
  label: "Default license plate formatter settings"
  mapping:
    concatenated:
      type: boolean
      label: "Whether to concatenate the two fields number and code into one single span tag."

# @see Drupal\eg_license_plate\Plugin\Field\FieldType\LicensePlateItem::fieldSettingsForm
# The `license_plate_type` part is a made-up setting name of our choice.
field.field_settings.license_plate_type:
  type: mapping
  label: 'License plate field settings'
  mapping:
    codes:
      type: string
      label: 'Codes'